"""baseline_all_tables

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-05-25 21:38:59.777967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('STARTER', 'GROWTH', 'ENTERPRISE', 'INTERNAL', name='billingplantier'), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('monthly_price_usd', sa.Float(), nullable=False),
    sa.Column('max_conversations_per_month', sa.Integer(), nullable=False),
    sa.Column('max_voice_minutes_per_month', sa.Integer(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('max_llm_cost_usd_per_month', sa.Float(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_plans_tier'), ['tier'], unique=True)

    op.create_table('intelligence_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('kind', sa.Enum('MANUAL', 'WEBSITE', 'GOOGLE_PLACES', 'X_API', 'REDDIT_API', 'CRM', name='intelligencesourcekind'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('domain', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('CUSTOMER', 'OPERATOR', 'ADMIN', name='rolename'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('default_language', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('whatsapp_phone_number_id', sa.String(length=120), nullable=True),
    sa.Column('emergency_disclaimer', sa.Text(), nullable=False),
    sa.Column('ai_auto_reply_threshold', sa.Float(), nullable=False),
    sa.Column('shadow_review_threshold', sa.Float(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinics_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinics_slug'), ['slug'], unique=True)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=140), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('external_ref', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELLED', 'TRIAL', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_metric_key'), ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_period_start'), ['period_start'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='appointmentstatus'), nullable=False),
    sa.Column('confirmation_code', sa.String(length=40), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_code')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinic_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('working_hours_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_branches_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('clinic_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'OPERATOR', 'CLINICIAN', name='clinicuserrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'user_id', name='uq_clinic_membership_user')
    )
    with op.batch_alter_table('clinic_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_memberships_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('clinic_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('source', sa.Enum('WHATSAPP', 'WEB_CHAT', 'PHONE', 'MANUAL', name='clinicchannel'), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('data_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'phone', name='uq_clinic_patient_phone')
    )
    with op.batch_alter_table('clinic_patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_patients_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_patients_data_expires_at'), ['data_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_patients_phone'), ['phone'], unique=False)

    op.create_table('enterprise_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=140), nullable=False),
    sa.Column('availability_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_inbound_events_provider_external')
    )
    with op.batch_alter_table('inbound_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_events_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_events_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_events_provider'), ['provider'], unique=False)

    op.create_table('intelligence_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('target_location', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'BLOCKED', name='intelligencejobstatus'), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('agent_type', sa.String(length=60), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_records_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_records_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_records_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_records_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_records_user_id'), ['user_id'], unique=False)

    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'FAILED', 'DEAD_LETTER', name='outboxeventstatus'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_status'), ['status'], unique=False)

    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('confidence_boost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=120), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=True),
    sa.Column('result_status', sa.Enum('SUCCESS', 'FAILURE', 'INFO', name='auditresultstatus'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='messagesender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinic_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'WEB_CHAT', 'PHONE', 'MANUAL', name='clinicchannel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WAITING_HUMAN', 'APPOINTMENT_PENDING', 'CLOSED', name='clinicconversationstatus'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('intent', sa.Enum('BOOK_APPOINTMENT', 'RESCHEDULE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'ASK_PRICE', 'ASK_INSURANCE', 'ASK_LOCATION', 'ASK_WORKING_HOURS', 'MEDICAL_EMERGENCY', 'GENERAL_QUESTION', 'UNKNOWN', name='clinicintent'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_patient_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_thread_id', sa.String(length=160), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('data_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['clinic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_conversations_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_conversations_data_expires_at'), ['data_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_conversations_external_thread_id'), ['external_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_conversations_patient_id'), ['patient_id'], unique=False)

    op.create_table('enterprise_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NEEDS_HUMAN', 'CLOSED', name='enterprisesessionstatus'), nullable=False),
    sa.Column('intent', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('handoff_package', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['enterprise_customers.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('source_url', sa.String(length=700), nullable=True),
    sa.Column('source_kind', sa.Enum('MANUAL', 'WEBSITE', 'GOOGLE_PLACES', 'X_API', 'REDDIT_API', 'CRM', name='intelligencesourcekind'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('consent_basis', sa.String(length=80), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['intelligence_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=60), nullable=False),
    sa.Column('intent', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_decision_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_intent'), ['intent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_requires_human'), ['requires_human'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_risk'), ['risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_decision_logs_user_id'), ['user_id'], unique=False)

    op.create_table('clinic_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Enum('PATIENT', 'ASSISTANT', 'OPERATOR', 'SYSTEM', name='clinicmessagesender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('intent', sa.Enum('BOOK_APPOINTMENT', 'RESCHEDULE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'ASK_PRICE', 'ASK_INSURANCE', 'ASK_LOCATION', 'ASK_WORKING_HOURS', 'MEDICAL_EMERGENCY', 'GENERAL_QUESTION', 'UNKNOWN', name='clinicintent'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('external_message_id', sa.String(length=160), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_messages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_messages_external_message_id'), ['external_message_id'], unique=False)

    op.create_table('clinical_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=140), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='clinicalappointmentstatus'), nullable=False),
    sa.Column('external_ref', sa.String(length=140), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['clinic_branches.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['clinic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_appointments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_appointments_patient_id'), ['patient_id'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('consent_type', sa.Enum('VOICE_RECORDING', 'DATA_PROCESSING', 'CROSS_BORDER_TRANSFER', 'INSURANCE_LOOKUP', name='consenttype'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'WEB_CHAT', 'PHONE', 'MANUAL', name='clinicchannel'), nullable=True),
    sa.Column('ip_or_device_hint', sa.String(length=120), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_text_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['clinic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_consent_type'), ['consent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_patient_id'), ['patient_id'], unique=False)

    op.create_table('enterprise_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('intent', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'ESCALATED', 'CLOSED', name='enterpriseticketstatus'), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('handoff_package', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['enterprise_agents.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['enterprise_customers.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['enterprise_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frustration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('message_excerpt', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frustration_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frustration_logs_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('lead_contact_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('PHONE', 'EMAIL', 'URL', 'SOCIAL', name='leadcontactkind'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('normalized_value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=700), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SENT', 'REJECTED', name='outreachdraftstatus'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['clinic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pre_intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_intakes_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_intakes_patient_id'), ['patient_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'WEB_CHAT', 'PHONE', 'MANUAL', name='clinicchannel'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'FAILED', name='reminderstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['clinical_appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('shadow_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('patient_message_id', sa.Integer(), nullable=False),
    sa.Column('draft_reply', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('BOOK_APPOINTMENT', 'RESCHEDULE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'ASK_PRICE', 'ASK_INSURANCE', 'ASK_LOCATION', 'ASK_WORKING_HOURS', 'MEDICAL_EMERGENCY', 'GENERAL_QUESTION', 'UNKNOWN', name='clinicintent'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risk_reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', name='shadowreviewstatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_reply', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_message_id'], ['clinic_messages.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shadow_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shadow_reviews_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_reviews_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shadow_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shadow_reviews_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_shadow_reviews_clinic_id'))

    op.drop_table('shadow_reviews')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_appointment_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('pre_intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_intakes_patient_id'))
        batch_op.drop_index(batch_op.f('ix_pre_intakes_clinic_id'))

    op.drop_table('pre_intakes')
    op.drop_table('outreach_drafts')
    op.drop_table('lead_contact_points')
    with op.batch_alter_table('frustration_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frustration_logs_clinic_id'))

    op.drop_table('frustration_logs')
    op.drop_table('enterprise_tickets')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_patient_id'))
        batch_op.drop_index(batch_op.f('ix_consent_records_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_consent_records_consent_type'))
        batch_op.drop_index(batch_op.f('ix_consent_records_clinic_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('clinical_appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_appointments_clinic_id'))

    op.drop_table('clinical_appointments')
    with op.batch_alter_table('clinic_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_messages_external_message_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_messages_clinic_id'))

    op.drop_table('clinic_messages')
    with op.batch_alter_table('agent_decision_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_risk'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_requires_human'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_intent'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_chat_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_decision_logs_agent_type'))

    op.drop_table('agent_decision_logs')
    op.drop_table('leads')
    op.drop_table('enterprise_sessions')
    with op.batch_alter_table('clinic_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_conversations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_conversations_external_thread_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_conversations_data_expires_at'))
        batch_op.drop_index(batch_op.f('ix_clinic_conversations_clinic_id'))

    op.drop_table('clinic_conversations')
    op.drop_table('chat_messages')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_clinic_id'))

    op.drop_table('audit_logs')
    op.drop_table('routing_rules')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_next_retry_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_clinic_id'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('llm_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_provider'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_model'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_agent_type'))

    op.drop_table('llm_usage_records')
    op.drop_table('intelligence_jobs')
    with op.batch_alter_table('inbound_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_events_provider'))
        batch_op.drop_index(batch_op.f('ix_inbound_events_external_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_events_clinic_id'))

    op.drop_table('inbound_events')
    op.drop_table('enterprise_agents')
    with op.batch_alter_table('clinic_patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_clinic_patients_data_expires_at'))
        batch_op.drop_index(batch_op.f('ix_clinic_patients_clinic_id'))

    op.drop_table('clinic_patients')
    with op.batch_alter_table('clinic_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_memberships_clinic_id'))

    op.drop_table('clinic_memberships')
    with op.batch_alter_table('clinic_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_branches_clinic_id'))

    op.drop_table('clinic_branches')
    op.drop_table('chat_sessions')
    op.drop_table('appointments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_period_start'))
        batch_op.drop_index(batch_op.f('ix_usage_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_metric_key'))

    op.drop_table('usage_records')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_organization_id'))

    op.drop_table('subscriptions')
    op.drop_table('enterprise_customers')
    op.drop_table('departments')
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_slug'))
        batch_op.drop_index(batch_op.f('ix_clinics_organization_id'))

    op.drop_table('clinics')
    op.drop_table('roles')
    op.drop_table('organizations')
    op.drop_table('intelligence_sources')
    with op.batch_alter_table('billing_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_plans_tier'))

    op.drop_table('billing_plans')
    op.drop_table('appointment_slots')
    # ### end Alembic commands ###
