"""initial

Revision ID: ff0507ce5844
Revises: 
Create Date: 2026-05-09 03:08:10.579772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ff0507ce5844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('default_language', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('whatsapp_phone_number_id', sa.String(length=120), nullable=True),
    sa.Column('emergency_disclaimer', sa.Text(), nullable=False),
    sa.Column('ai_auto_reply_threshold', sa.Float(), nullable=False),
    sa.Column('shadow_review_threshold', sa.Float(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinics_slug'), ['slug'], unique=True)

    op.create_table('clinic_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('working_hours_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_branches_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('clinic_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('source', sa.Enum('WHATSAPP', 'WEB_CHAT', 'PHONE', 'MANUAL', name='clinicchannel'), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'phone', name='uq_clinic_patient_phone')
    )
    with op.batch_alter_table('clinic_patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_patients_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_patients_phone'), ['phone'], unique=False)

    op.create_table('clinic_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'WEB_CHAT', 'PHONE', 'MANUAL', name='clinicchannel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WAITING_HUMAN', 'APPOINTMENT_PENDING', 'CLOSED', name='clinicconversationstatus'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('intent', sa.Enum('BOOK_APPOINTMENT', 'RESCHEDULE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'ASK_PRICE', 'ASK_INSURANCE', 'ASK_LOCATION', 'ASK_WORKING_HOURS', 'MEDICAL_EMERGENCY', 'GENERAL_QUESTION', 'UNKNOWN', name='clinicintent'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_patient_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_thread_id', sa.String(length=160), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['clinic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_conversations_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_conversations_external_thread_id'), ['external_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_conversations_patient_id'), ['patient_id'], unique=False)

    op.create_table('clinic_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'OPERATOR', 'CLINICIAN', name='clinicuserrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'user_id', name='uq_clinic_membership_user')
    )
    with op.batch_alter_table('clinic_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_memberships_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('clinic_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Enum('PATIENT', 'ASSISTANT', 'OPERATOR', 'SYSTEM', name='clinicmessagesender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('intent', sa.Enum('BOOK_APPOINTMENT', 'RESCHEDULE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'ASK_PRICE', 'ASK_INSURANCE', 'ASK_LOCATION', 'ASK_WORKING_HOURS', 'MEDICAL_EMERGENCY', 'GENERAL_QUESTION', 'UNKNOWN', name='clinicintent'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('external_message_id', sa.String(length=160), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_messages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_messages_external_message_id'), ['external_message_id'], unique=False)

    op.create_table('clinical_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=140), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='clinicalappointmentstatus'), nullable=False),
    sa.Column('external_ref', sa.String(length=140), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['clinic_branches.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['clinic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_appointments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_appointments_patient_id'), ['patient_id'], unique=False)

    op.create_table('frustration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('message_excerpt', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frustration_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frustration_logs_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('pre_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['clinic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pre_intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_intakes_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_intakes_patient_id'), ['patient_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'WEB_CHAT', 'PHONE', 'MANUAL', name='clinicchannel'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'FAILED', name='reminderstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['clinical_appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('shadow_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('patient_message_id', sa.Integer(), nullable=False),
    sa.Column('draft_reply', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('BOOK_APPOINTMENT', 'RESCHEDULE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'ASK_PRICE', 'ASK_INSURANCE', 'ASK_LOCATION', 'ASK_WORKING_HOURS', 'MEDICAL_EMERGENCY', 'GENERAL_QUESTION', 'UNKNOWN', name='clinicintent'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risk_reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', name='shadowreviewstatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_reply', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['clinic_conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_message_id'], ['clinic_messages.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shadow_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shadow_reviews_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_reviews_conversation_id'), ['conversation_id'], unique=False)

    op.drop_table('knowledge_articles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_sessions', ['session_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_sessions', ['session_id'], ['id'])

    op.create_table('knowledge_articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=180), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shadow_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shadow_reviews_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_shadow_reviews_clinic_id'))

    op.drop_table('shadow_reviews')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_appointment_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('pre_intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_intakes_patient_id'))
        batch_op.drop_index(batch_op.f('ix_pre_intakes_clinic_id'))

    op.drop_table('pre_intakes')
    with op.batch_alter_table('frustration_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frustration_logs_clinic_id'))

    op.drop_table('frustration_logs')
    with op.batch_alter_table('clinical_appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_appointments_clinic_id'))

    op.drop_table('clinical_appointments')
    with op.batch_alter_table('clinic_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_messages_external_message_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_messages_clinic_id'))

    op.drop_table('clinic_messages')
    with op.batch_alter_table('clinic_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_memberships_clinic_id'))

    op.drop_table('clinic_memberships')
    with op.batch_alter_table('clinic_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_conversations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_conversations_external_thread_id'))
        batch_op.drop_index(batch_op.f('ix_clinic_conversations_clinic_id'))

    op.drop_table('clinic_conversations')
    with op.batch_alter_table('clinic_patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_clinic_patients_clinic_id'))

    op.drop_table('clinic_patients')
    with op.batch_alter_table('clinic_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_branches_clinic_id'))

    op.drop_table('clinic_branches')
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_slug'))

    op.drop_table('clinics')
    # ### end Alembic commands ###
